language: node_js
node_js:
  - "0.12"

sudo: false

before_install:
  - npm install grunt-cli -g

addons:
  apt:
    packages:
      - gcc

deploy:
  provider: npm
  email: ceberhardt@scottlogic.com
  api_key:
    secure: "KTmVyw8YdArB5xWgNbkeZ9JD1jAKh/uMjWJdjjDfTBxKVarFfyP5+899C+qZJ8f7cAfiHZKwNE5nCjfU6uuFjYc7gMFr/ezm1KZc1DXM51V6B9TnIwLxNBr5ZYwcW7H725iYpQMwXX9rC/W4U8mahMKo8m7L0DQGUWEoYuGkKd8="
  on:
    tags: true
    branch: master