# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

os: osx
osx_image: xcode8.2
language: cpp
compiler: clang

env:
  - LANG=c
  - LANG=java
  - LANG=net
  - LANG=ios
  - LANG=js

before_install:
  - brew update
  - brew tap facebook/fb
  - brew install buck

  # Java
  - |
    [[ $LANG = "java" ]] &&
    brew cask install java &&
    export JAVA_HOME=$(/usr/libexec/java_home -v 1.8) &&
    export PATH=$JAVA_HOME/bin:$PATH

  # .NET
  - |
    [[ $LANG = "net" ]] &&
    brew install mono

  # iOS
  - |
    [[ $LANG = "ios" ]] &&
    brew upgrade xctool

  # JavaScript
  - |
    [[ $LANG = "js" ]] &&
    cd javascript &&
    npm install

script:
    # C
    - |
      [[ $LANG = "c" ]] &&
      buck test //:yoga &&
      buck run //benchmark:benchmark &&
      git checkout HEAD^ &&
      buck run //benchmark:benchmark

    # Java
    - |
      [[ $LANG = "java" ]] &&
      buck test //java:java

    # .NET
    - |
      [[ $LANG = "net" ]] &&
      sh csharp/tests/Facebook.Yoga/test_macos.sh

    # iOS
    - |
      [[ $LANG = "ios" ]] &&
      buck test //YogaKit:YogaKitTests --config cxx.default_platform=iphonesimulator-x86_64

    # JavaScript
    - |
      [[ $LANG = "js" ]] &&
      npm run test:all &&
      npm run bench
