language:
  - c
  - java

compiler: clang

install:
  - git clone https://github.com/facebook/buck.git /home/ubuntu/buck
  - cd /home/ubuntu/buck && ant
  - buck --version

script:
  - buck test //:CSSLayout
  - buck test //:CSSLayout_java
  - buck run  //:CSSLayout:benchmark
